
package com.epam;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorSOAPServiceService", targetNamespace = "http://SOAPService.services.epam.com/", wsdlLocation = "http://localhost:8080/epam/services/calculatorSOAP?wsdl")
public class CalculatorSOAPServiceService
    extends Service
{

    private final static URL CALCULATORSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORSOAPSERVICESERVICE_EXCEPTION;
    private final static QName CALCULATORSOAPSERVICESERVICE_QNAME = new QName("http://SOAPService.services.epam.com/", "CalculatorSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/epam/services/calculatorSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORSOAPSERVICESERVICE_WSDL_LOCATION = url;
        CALCULATORSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public CalculatorSOAPServiceService() {
        super(__getWsdlLocation(), CALCULATORSOAPSERVICESERVICE_QNAME);
    }

    public CalculatorSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORSOAPSERVICESERVICE_QNAME, features);
    }

    public CalculatorSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORSOAPSERVICESERVICE_QNAME);
    }

    public CalculatorSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORSOAPSERVICESERVICE_QNAME, features);
    }

    public CalculatorSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorSOAPService
     */
    @WebEndpoint(name = "CalculatorSOAPServicePort")
    public CalculatorSOAPService getCalculatorSOAPServicePort() {
        return super.getPort(new QName("http://SOAPService.services.epam.com/", "CalculatorSOAPServicePort"), CalculatorSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorSOAPService
     */
    @WebEndpoint(name = "CalculatorSOAPServicePort")
    public CalculatorSOAPService getCalculatorSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAPService.services.epam.com/", "CalculatorSOAPServicePort"), CalculatorSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw CALCULATORSOAPSERVICESERVICE_EXCEPTION;
        }
        return CALCULATORSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
